name: Renovate

on: pull_request

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/bun.yml@main
    with:
      disable-test: true
      disable-build: true

  auto-merge:
    needs: test
    uses: winstxnhdw/actions/.github/workflows/renovate-public.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
